   Welcome to

       IIIII             tt                                         dd
        III              tt                               ii        dd
        III            tttttt                                       dd
        III    nnnnn     tt    rr  rrr   eeee    ppppp    ii    dddddd
        III    nn  nn    tt     rrrr    ee  ee  pp   pp   ii   dd   dd
        III    nn  nn    tt     rrr     eeeee   pp    pp  ii  dd    dd
        III    nn  nn    tt     rr      ee      pp   pp   ii   dd   dd
       IIIII   nn  nn     ttt   rr       eeee   pppppp    ii    dddddd
                                                pp
         MUD                                    pp
                                                pp

      server6.mecho.network 8765       Your administrators are
                                       Segtor  HawkEyE  beaver  Tandon

