###########################################################################
#
# IntrepidMUD Configuration File
# Copyright 2007- by Segtor, HawkEyE, blimey, Ghostrider
# For licensing details, see docs/License.txt
#
###########################################################################

#
# The name of the MUD
mud_name:		IntrepidMUD

#
# The port number on which the MUD will run
# Note: * This must be between 1024 and 31999
#       * The InterMUD server, if defined, will run on a port one above the
#		  MUD itself, so make sure it is free
port:			8765

#
# Time format
time_format:		eu

#
# Hard coded administrators
hardcoded:		segtor hawkeye beaver tandon

#
# Hard coded password
hc_passwd:		ax9kg23zop3xz44j

#
# Hero level
hero:			100

#
# Default level for the first character of a hardcoded logging in for the
# first time
hc_level:		110
