###########################################################################
#
# IntrepidMUD Configuration File
# Copyright 2007- by Segtor, HawkEyE, blimey, Ghostrider
# For licensing details, see docs/License.txt
#
###########################################################################

#
# Message to show when we're full
full:		We're sorry, but the MUD is currently full. Please try
		again later.

#
# Message to show when disconnecting the user for taking too long to log in
# or when steps in the character creation process take too long
too_long_time:	You have been disconnected for taking too long.

#
# Instructions to login or start a new character
login_instr:	If you are an existing user, please enter your username.
		Otherwise, please type "new" to proceed to registering your
		character. You may also type "who" to see who is on the MUD, as well
		as "quit" to quit the login process.

#
# Color question
want_color:	This MUD supports color using multiple terminal emulations. If
		you want to use color, please type "yes" at the following
		prompt, and this MUD software will default to vt100 emulation.

#
# New user name
new_name:	Welcome to IntrepidMUD! Please select a username to proceed into
		the new user creation.

#
# Password
enter_pwd:	Please enter your password. IntrepidMUD uses the password to
		uniquely identify your account, as well as to protect it and your
		character(s) from inadvertent or intentional use by another user.

#
# Password (2)
re_pwd:		Please repeat your password, so that this MUD can be certain that
		you haven't accidentally mistyped it.

#
# Password failed
failed_pwd:	I am sorry to say, but you have failed to match your password three
		times in a row. Please try again later, but for now... Goodbye!

#
# Hard-Coded
hardcoded:	Your name matches the name of one of the hard coded
		administrators of this MUD. Please enter the hard coded administrator
		password.

#
# Message of the Day
motd:		Currently IntrepidMUD is going through a serious development
		phase, mostly running under gdb when it's up at all.

#
# Select character
character:	Please select your character. You may also type "create" to
		create a new character.

#
# Character not found
char_not_found:	A character by the name you entered was not found in your
		characters, please try again.

#
# Selecting race
select_race:	Please select your characters race, from any of the
		following:

#
# Selecting class
select_class:	Please select your characters class, from any of the
		following:

#
# Pick the first name
pick_firstname:	Please give us your characters first name. The first name
		is how you will be addressed by people you know.

#
# Pick the family name
pick_familyname:	Please give us your characters family name. The
			family name is, together with the gender-specific
			honorific (like Mr), people who don't really know
			you address you.

#
# Pick gender
pick_gender:	Please give us your characters gender. Gender options are
		M for male, F for female and N for neuter.

#
# Pick alignment
pick_align:	Please give us your characters alignment. Alignment options
		are G for good, N for neutral and E for evil. Later on during
		the character creation process, you will get to pick your
		characters ethos.

#
# Pick ethos
pick_ethos:	Please give us your characters ethos. Ethos options are
		L for lawful, N for neutral and C for chaotic.
