###########################################################################
#
# IntrepidMUD Configuration File
# Copyright 2007- by Segtor, HawkEyE, blimey, Ghostrider
# For licensing details, see docs/License.txt
#
###########################################################################

#
# Default prompt
default_prompt:	IntrepidMUD> 

#
# Asking for enter
press_enter:	Please press <ENTER> to proceed: 

#
# Asking for username
username:	Please enter your username: 

#
# Asking for a new username
new_name:	Please enter your desired username: 

#
# Asking for color support
want_color:	Type "yes" if you want color: 

#
# Asking for password
enter_pwd:	Please enter your password: 
