#!/bin/sh
#
# make_pretty
# Written by Silver (15.12.97)
# Updated by blimey (09.08.98)
# Updated by Griff (27.04.12)
# Updated by Segtor (30.01.18)
#
# This batch file makes a backup of your src files (just in case)
# and then formats every .c file in the source dirs and every .h file
# in the include dir nicely.
#
# You can change the flags that "indent" uses by editing the ident line
# although the one here should suffice
#
# This file is copied from Playground Plus and modified to fit IntrepidMUD
#

if [ ! -e .indent.pro -a ! -e $HOME/.indent.pro ] ; then
  INDENT_OPTIONS="-linux -bbo -bl -bli0 -blf -bls -ci2 -cs -hnl -i2 -l75 -lp -nlps -ncdw -nce -ncs -npcs -nprs -npsl -nsob -nss -nut -saf -sai -saw -ts8"
fi

echo "Make_Pretty 1.1"
echo "A batch file written by Silver (15.12.1997)"
echo "Edited and updated by Griff"
echo "Updated and modified for IntrepidMUD by Segtor"
echo " "
echo "Backing up your code (just in case)"

rm -f backup.tar.gz
tar -cf - */*.[ch] | gzip -c > backup.tar.gz

rm -f mp_temp
for id in angel/*.c
do
  echo "Tidying up '$id' ..."
  indent $INDENT_OPTIONS $id -o mp_temp
  mv mp_temp $id
done
for id in archangel/*.c
do
  echo "Tidying up '$id' ..."
  indent $INDENT_OPTIONS $id -o mp_temp
  mv mp_temp $id
done
for id in common/*.c
do
  echo "Tidying up '$id' ..."
  indent $INDENT_OPTIONS $id -o mp_temp
  mv mp_temp $id
done
for id in dns/*.c
do
  echo "Tidying up '$id' ..."
  indent $INDENT_OPTIONS $id -o mp_temp
  mv mp_temp $id
done
for id in ident/*.c
do
  echo "Tidying up '$id' ..."
  indent $INDENT_OPTIONS $id -o mp_temp
  mv mp_temp $id
done
for id in intermud/*.c
do
  echo "Tidying up '$id' ..."
  indent $INDENT_OPTIONS $id -o mp_temp
  mv mp_temp $id
done
for id in mud/*.c
do
  echo "Tidying up '$id' ..."
  indent $INDENT_OPTIONS $id -o mp_temp
  mv mp_temp $id
done
for id in include/*.h
do
  echo "Tidying up '$id' ..."
  indent $INDENT_OPTIONS $id -o mp_temp
  mv mp_temp $id
done

echo " "
echo "Finished"
echo " "
echo "It is recommended you do a 'make reinstall' now to check that the code"
echo "still compiles fine. If in the unlikely event that it doesn't then"
echo "you can restore the src files from the 'backup.tar.gz' file with"
echo "the command 'gzip -dc backup.tar.gz | tar -xf -'"
echo " "
